<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Requisition Report</title>
    <style>
        @page {
            margin: 0;
        }
        body {
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
            background-image: url('{{ public_path('images/backgrounds/report-bg.jpg') }}');
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }
        .content {
            padding: 40px;
            background: rgba(255, 255, 255, 0.9);
            margin: 20px;
            border-radius: 10px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 3px solid #2c3e50;
        }
        .header h1 {
            color: #2c3e50;
            margin: 0;
            font-size: 28px;
        }
        .header .date {
            color: #7f8c8d;
            font-size: 16px;
            margin-top: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #34495e;
            color: white;
            padding: 12px 8px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 10px 8px;
            border-bottom: 1px solid #ecf0f1;
        }
        tr:nth-child(even) {
            background-color: #fef9f9ff;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #7f8c8d;
            font-size: 14px;
            padding-top: 20px;
            border-top: 1px solid #ecf0f1;
        }
        .logo {
            width: 110px;
            height: auto;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="content">
        <div class="header">
            <h1>Internal Stock Requisition Report</h1>
            <div class="date">Generated on: {{ now()->format('F j, Y \a\t g:i A') }}</div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Req No</th>
                    <th>Item</th>
                    <th>Description</th>
                    <th>Quantity</th>
                    <th>Urgency</th>
                    <th>Status</th>
                    <th>Requested By</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($requisitions as $r)
                <tr>
                    <td>{{ $r->requisition_no ?? 'N/A' }}</td>
                    <td>{{ $r->item_name }}</td>
                    <td>{{ \Illuminate\Support\Str::limit($r->description, 50) }}</td>
                    <td>{{ $r->quantity }}</td>
                    <td>
                        <span style="background: {{ $r->urgency == 'high' ? '#e74c3c' : ($r->urgency == 'medium' ? '#f39c12' : '#27ae60') }}; 
                              color: white; padding: 2px 8px; border-radius: 4px; font-size: 12px;">
                            {{ ucfirst($r->urgency) }}
                        </span>
                    </td>
                    <td>{{ ucfirst($r->status) }}</td>
                    <td>{{ $r->user->name }}</td>
                    <td>{{ $r->created_at->format('Y-m-d') }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div class="footer">
            <p>Generated by Stock Requisition Management System</p>
            <p>Total Requisitions: {{ $requisitions->count() }}</p>
        </div>
    </div>
</body>
</html>