<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Requisition Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #dee2e6;
        }
        .header h1 {
            color: #2c3e50;
            margin: 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #f8f9fa;
            padding: 12px 8px;
            text-align: left;
            font-weight: bold;
            border: 1px solid #dee2e6;
        }
        td {
            padding: 10px 8px;
            border: 1px solid #dee2e6;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #6c757d;
            font-size: 0.9em;
        }
        .status-badge {
            padding: 4px 8px;
            border-radius: 12px;
            font-size: 0.8em;
            font-weight: bold;
        }
        .status-pending { background-color: #6c757d; color: white; }
        .status-bought { background-color: #17a2b8; color: white; }
        .status-done { background-color: #007bff; color: white; }
        .status-paid { background-color: #28a745; color: white; }
        .urgency-high { background-color: #dc3545; color: white; }
        .urgency-medium { background-color: #ffc107; color: black; }
        .urgency-low { background-color: #28a745; color: white; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Requisition Report</h1>
        <p>Generated on: {{ now()->format('F j, Y \a\t g:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Req No</th>
                <th>Item</th>
                <th>User</th>
                <th>Qty</th>
                <th>Urgency</th>
                <th>Status</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($requisitions as $req)
            <tr>
                <td>{{ $req->requisition_no ?? 'N/A' }}</td>
                <td>{{ $req->item_name }}</td>
                <td>{{ $req->user->name }}</td>
                <td>{{ $req->quantity }}</td>
                <td>
                    <span class="status-badge urgency-{{ $req->urgency }}">
                        {{ ucfirst($req->urgency) }}
                    </span>
                </td>
                <td>
                    <span class="status-badge status-{{ $req->status }}">
                        {{ ucfirst($req->status) }}
                    </span>
                    @if($req->status === 'done' && $req->received_confirmed)
                        <span class="status-badge status-paid">
                            Received
                        </span>
                    @endif
                </td>
                <td>{{ $req->created_at->format('Y-m-d') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Stock Requisition System • {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>
